### ISSUE TITLE
No longer estimating salaries - seek look to have changed layout

### ISSUE THREAD

**Issue by marija222** [cheesestringer/salary-seeker#16]
Salary estimator no longer works, layout has changed on seek so not sure if that has impacted it?

**Comment by ThinkFishNaught** [comment]
Also having same issue.

**Comment by cheesestringer** [comment]
As a temporary work around you can refresh the page and it should load the salary. I'll dig in to why this is failing though, thanks for reporting!!

**Comment by ThinkFishNaught** [comment]
The refresh didn't work for me, I'm on Chrome Version 90.0.4430.72 (Official Build) (64-bit).
Thanks, for providing this tool its proved invaluable.

**Comment by cheesestringer** [comment]
Seek still shows the old and new experience so that's why refreshing worked for me but not for you. This should be fixed now just waiting for the extension stores to approve the changes.

In case this breaks again in the future I've added the ability for you to click the salary seeker icon to see your recent jobs.

![image](https://user-images.githubusercontent.com/4462478/115987030-adb83300-a5f6-11eb-8db2-f41e4e4eb134.png)

**Comment by marija222** [comment]
Will the ability to click salary seeker to see recent jobs come through once changes are approved?

**Comment by cheesestringer** [comment]
Yep!

**Comment by cheesestringer** [comment]
Update is live, let me know if there are any issues.

**Comment by marija222** [comment]
Perfect, all working now! Thank you :)
